config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # FIXME there are some excessive routes

  get '/adopt/dogs' => 'animals#dogs', as: :dogs_index
  get '/adopt/dogs/:petfinder_id' => 'animals#dog', as: :dog
  get '/adopt/birds' => 'animals#birds', as: :birds_index
  get '/adopt/birds/:petfinder_id' => 'animals#bird', as: :bird
  get '/adopt/cats' => 'animals#cats', as: :cats_index
  get '/adopt/cats/:petfinder_id' => 'animals#cat', as: :cat
  get '/adopt/rabbits' => 'animals#rabbits', as: :rabbits_index
  get '/adopt/rabbits/:petfinder_id' => 'animals#rabbit', as: :rabbit
  get '/adopt/small_animals' => 'animals#small_animals', as: :small_animals_index
  get '/adopt/small_animals/:petfinder_id' => 'animals#small_animal', as: :small_animal
  get '/adopt/horses' => 'animals#horses', as: :horses_index
  get '/adopt/horses/:petfinder_id' => 'animals#horse', as: :horse

  resources :applicants, :events, :submissions

  resources :news, only: :index

  #adoption_form_id = SubmissionTemplate.where(id: @submission_template_id)
  get "/adoption_form", #?submission_template_id=#{adoption_form_id}",
      to: "public#new",
      as: 'adoption_form'
  post '/adoption_form',
       to: 'public#create',
       as: 'adoption_submission'

  get  '/thanks',
       to: 'public#submission_thank_you',
       as: 'submission_thank_you'
  post '/thanks',
       to: 'public#submission_thank_you',
       as: ''


  resources :submission_templates, only: [ :index, :update ]
  put '/submission_templates',
      to: 'submission_templates#update',
      as: 'new_submission_template'

  resources :submission_template_questions, only: [ :index, :update ]
  put '/submission_template_questions',
      to: 'submission_template_questions#update',
      as: 'new_submission_template_question'

  resources :questions, only: [ :index, :update, :destroy ]
  put '/questions',
      to: 'questions#update',
      as: 'update_question'
  put '/questions',
      to: 'questions#delete',
      as: 'delete_question'




  cms_fortress_routes :path => '/cms-admin'

  comfy_route :blog_admin, :path => '/admin'
  comfy_route :blog, :path => '/blog'

  comfy_route :cms_admin, :path => '/admin'

  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false

end

app/models/event.rb
class Event < ActiveRecord::Base


  def date_as_date
    Date.strptime(self.date, '%m/%d/%Y')
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def destroy
    @event.destroy
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  def update
    @event.update(event_params)
    redirect_to events_path
  end

  private def set_event
    @event = Event.find(params[:id])
  end

  private def event_params
    params.require(:event).permit(:date, :title, :description)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<h3 class="event-title">Add an Event</h3>

<div class="container">
  <%= form_for @event do |f| %>
    <div class="row">
      <div class="form-group col-md-6 col-md-offset-1">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group col-md-4">
        <%= f.label :date%>
        <%= f.text_field :date, class: 'form-control' %>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-10 col-md-offset-1">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control', rows: "10" %>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-md-10 col-md-offset-1">
        <%= f.submit class: "btn btn-default event-submit" %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<%= render 'form' %>

app/views/events/index.html.erb
<div class="container">
  <h1>Events</h1>

  <%= link_to raw("<span class='glyphicon glyphicon-plus' aria-hidden='true'></span> Add New Event"), new_event_path, class: 'btn btn-default btn-primary new_event' %>
  <br><br>

  <div class="table-responsive">
	<table class="event-list table table-condensed">
	    <tr>
		<th>Date</th>
		<th>Title</th>
		<th>Description</th>
		<th>Edit</th>
		<th>Delete</th>
	    </tr>
	  <% @events.each do |e| %>
	    <tr>
	      <td> <%= e.date %></td>
	      <td><%= e.title %></td>
	      <td><%= e.description %></td>
	      <td>
		<%= link_to raw("<span class='glyphicon glyphicon-pencil' aria-hidden='true'></span>"), edit_event_path(e), class: 'btn btn-warning edit_event' %>
	      </td>
	      <td>
		<%= link_to(raw("<span class='glyphicon glyphicon-trash' aria-hidden='true'></span>"), e, :method => :delete, class: 'btn btn-danger delete_event', remote: true, data: { confirm: "Are you sure you want to delete this event?" }) %>
	      </td>
	    </tr>
	  <% end %>
	</table>
  </div>
</div>

app/views/events/new.html.erb
<%= render 'form' %>