config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  # FIXME there are some excessive routes

  get '/adopt/dogs' => 'animals#dogs', as: :dogs_index
  get '/adopt/dogs/:petfinder_id' => 'animals#dog', as: :dog
  get '/adopt/birds' => 'animals#birds', as: :birds_index
  get '/adopt/birds/:petfinder_id' => 'animals#bird', as: :bird
  get '/adopt/cats' => 'animals#cats', as: :cats_index
  get '/adopt/cats/:petfinder_id' => 'animals#cat', as: :cat
  get '/adopt/rabbits' => 'animals#rabbits', as: :rabbits_index
  get '/adopt/rabbits/:petfinder_id' => 'animals#rabbit', as: :rabbit
  get '/adopt/small_animals' => 'animals#small_animals', as: :small_animals_index
  get '/adopt/small_animals/:petfinder_id' => 'animals#small_animal', as: :small_animal
  get '/adopt/horses' => 'animals#horses', as: :horses_index
  get '/adopt/horses/:petfinder_id' => 'animals#horse', as: :horse

  resources :applicants, :events, :submissions

  resources :news, only: :index

  #adoption_form_id = SubmissionTemplate.where(id: @submission_template_id)
  get "/adoption_form", #?submission_template_id=#{adoption_form_id}",
      to: "public#new",
      as: 'adoption_form'
  post '/adoption_form',
       to: 'public#create',
       as: 'adoption_submission'

  get  '/thanks',
       to: 'public#submission_thank_you',
       as: 'submission_thank_you'
  post '/thanks',
       to: 'public#submission_thank_you',
       as: ''


  resources :submission_templates, only: [ :index, :update ]
  put '/submission_templates',
      to: 'submission_templates#update',
      as: 'new_submission_template'

  resources :submission_template_questions, only: [ :index, :update ]
  put '/submission_template_questions',
      to: 'submission_template_questions#update',
      as: 'new_submission_template_question'

  resources :questions, only: [ :index, :update, :destroy ]
  put '/questions',
      to: 'questions#update',
      as: 'update_question'
  put '/questions',
      to: 'questions#delete',
      as: 'delete_question'




  cms_fortress_routes :path => '/cms-admin'

  comfy_route :blog_admin, :path => '/admin'
  comfy_route :blog, :path => '/blog'

  comfy_route :cms_admin, :path => '/admin'

  # Make sure this routeset is defined last
  comfy_route :cms, :path => '/', :sitemap => false

end

app/models/submission.rb
class Submission < ActiveRecord::Base
  belongs_to :applicant, inverse_of: :submissions
  belongs_to :submission_template
  has_many   :responses
  has_many   :questions, through: :submission_template

  accepts_nested_attributes_for :responses

  def self.new_with_responses(submission_template_id)
    submission = self.new(submission_template_id: submission_template_id)
    submission.questions.order(:position).each do |q|
      submission.responses.build(question_id: q.id)
    end
    submission
  end
end

app/controllers/submissions_controller.rb
require "#{Rails.root}/app/helpers/application_helper.rb"
include ApplicationHelper

class SubmissionsController < ApplicationController
  # TODO add the logic for admin_only questions in the form

  respond_to :html, :json

  def index
    @submissions = Submission.includes(:applicant,
                                       {responses: :question},
                                       :submission_template).
                                        references(:applicant,
                                                   :questions,
                                                   :responses).
                                        order("submissions.id desc,
                                               questions.position,
                                               responses.id")
    @answered_question_names_array = Question.answered_question_names if Question.any?
  end

  def new
    @submission = Submission.new_with_responses(params[""])
    @submission.applicant.build
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to submissions_path,
                                  notice: 'Submission successfully created.' }
        format.json { render :new,
                             status: :created,
                             location: @submission }
      else
        format.html { render :new }
        format.json { render json: @submission.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  def edit
    @submission = Submission.find(params[:id]) if params[:id]
    @applicant = @submission.applicant

    @parent_questions = Question.where(id: Question.pluck(:parent_id).uniq)
  end

  def update
    @submission = Submission.find(params[:id]) if params[:id]
    @submission.update(submission_params)
    respond_with @submission
  end

  def show
    set_submission_template_variables
    @applicant = @submission.applicant if @submission
  end

  private def find_submission
    @submission = Submission.
        includes(submission_template: :pet_type).
        find(params[:id]) if params[:id]
  end

  private def set_submission_template_headers
    @submissions = Submission.includes({responses: :question}).
      references(:responses, :questions).
      order("submissions.id desc, questions.position, responses.id")
    @submission_template_headers =
      @submissions.last.submission_template.questions.
                                            order("questions.position").
                                            pluck(:name, :short_name)
  end

  private def set_submission_template_variables
    find_submission
    if @submission
      @submission_template = @submission.submission_template
    else
      @submission_template = SubmissionTemplate.first
    end
    @submission_template_form_name = @submission_template.name
    @submission_template_pet_type_name = @submission_template.pet_type.name
  end

  private def submission_params
    params.require(:submission).(:applicant_id,
                                 :submission_template_id,
                                 { responses_attributes:
                                     [ :id,
                                       :applicant_id,
                                       { :array_response => [] },
                                       :boolean_response,
                                       :date_response,
                                       :datetime_response,
                                       :integer_response,
                                       :question_id,
                                       :string_response,
                                       :submission_id,
                                       :text_response,
                                       :created_at,
                                       :updated_at,
                                       :_destroy ]
                                 },
    )
  end
end

app/helpers/submissions_helper.rb
module SubmissionsHelper

  def question_field_name(input_type)
    case
      when input_type == "date" then :date_response
      when input_type == "datetime" then :datetime_response
      when input_type == "integer" then :integer_response
      when input_type == "multiselect" then :array_response
      when input_type == "radio" ||
        input_type == "checkbox" then :string_response
      else :string_response
    end
  end

  def strip_hyphenated_string_to_downcase_prefix(string)
    string.gsub(/-.*$/, "").downcase
  end

  def validation_error_prompt(record)
    if record.errors.any?
      content_tag :div, "error-explanation", class: ["error-message"] do
        safe_join([
                    "<span class='glyphicon glyphicon-remove-sign'
                       aria-hidden='true'></span><h3>".html_safe,
                    (pluralize(record.errors.count, " issue" )) + " with your answers. " +
                      " (See below.) ", "<br/><br/>".html_safe,
                    "Click your browser's back button to fix and resubmit.",
                    "</h3>".html_safe,
                  record.errors.full_messages.each{ |message|
                    safe_join([
                      "<p>".html_safe,
                      message + ".",
                      "</p><br><hr><br/>".html_safe
                    ])
                  }
                  ])
      end
    end
  end

  def yes_no(val)
    if val === true
      "YES"
    elsif val === false
      "No"
    end
  end
end

app/views/submissions/_edit.html.erb
<div>

      <em><%= @submission.submission_template.andand.name %>:
        <%= @submission.created_at.strftime("%b %d %l:%M %p") %></p></em>

      <h1><%= link_to(@applicant.name, edit_applicant_path) %></h1>
      <p>Email_address:
        <% if @applicant.email_address.present? %>
          <%= mail_to(@applicant.email_address, @applicant.email_address.to_s,
                      subject: "Shakori Hills " + @submission
                         .submission_template.andand.name,
                      body: strip_tags(
                          "Dear " + @applicant.name + ",   "
                      )) %>
        <% else %>
          <%= "None on record." %>
        <% end %>
        <br>
      </p>
      <p>
        Home:
        <% if @applicant.home_telephone_number.present? %>
          <%= @applicant.home_telephone_number + "." %>
        <% else %>
          <%= "None on record. " %>
        <% end %>
        Work:
        <% if @applicant.work_telephone_number.present? %>
          <%= @applicant.work_telephone_number + "." %>
        <% else %>
          <%= "None on record. " %>
        <% end %>
        Mobile:
        <% if @applicant.mobile_telephone_number.present? %>
          <%= @applicant.mobile_telephone_number + "." %>
        <% else %>
          <%= "None on record. " %>
        <% end %>
      </p>
      <p>
        <%= "(" + @applicant.location + ")" if @applicant.location != nil %>
      </p>

      <br/>
      <hr>
    <div class="submission-form-fields field-section">
      <%= simple_form_for @submission do |submission_form| %>
        <%= render partial: "public/dynamic_submission_responses", locals: { submission_form: submission_form } %>

        <div class="submit-button">
          <%= submission_form.button :submit, "Submit", { class: "btn btn-primary" } %>
        </div>

      <% end %>
    </div>
</div>

app/views/submissions/_index.html.erb
<div class="col-md-12">
  <table class="table table-vertical-lines table-striped table-hover
                table-condensed table-responsive">
    <thead style="background-color: beige">
    <tr>
      <td>ID</td>
      <td>Submission_Template_Name</td>
      <td>Applicant_Name</td>
      <td>Email</td>
      <td>Home Phone</td>
      <td>DateTime_Created</td>
      <% @answered_question_names_array.each do |name, short_name| %>
        <td><%= short_name || name %></td>
      <% end%>
    </tr>
    </thead>

    <tbody>
    <% @submissions.each do |submission| %>
      <% if submission.applicant %>
        <tr>
          <td><%= submission.id %></td>
          <td><%= submission.submission_template.name %></td>
          <td><%= link_to(submission.applicant.name, edit_applicant_path(submission.applicant.id)) %></td>
          <td><% if submission.applicant.email_address %>
                <%= mail_to(submission.applicant.email_address) %>
              <% else %>
                <%= "No email on record." %>
              <% end %>
          </td>
          <td><%= submission.applicant.home_telephone_number %></td>
          <td><%= link_to(submission.created_at.strftime("%m/%d %l:%M %p"),
                          edit_submission_path(submission.id)) %></td>
          <% @answered_question_names_array.each do |question_name| %>
            <% question = Question.where(name: question_name).first %>
            <% if question.responses.where(submission: submission).any? %>
              <% response =
                     question.responses.where(submission: submission).first %><!--FIXME - assumes only one response-->
              <% input_type = question.input_type %>
                <% if input_type == "multiselect" %>
                  <td><%= response.array_response && response.array_response.
                      to_sentence || '._.' %></td>
                <% else %>
                  <td><%= response.send(question_field_name(input_type)) || '._.' %></td>
                <% end%>
            <% else %>
              <td></td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    <% end%>
    </tbody>
  </table>
</div>

app/views/submissions/edit.html.erb
<div class="submission-show">
  <div class="header-bar">
    <% if @submission %>
      <%= mail_to('', 'Email this Application',
                  subject: @submission.submission_template.name + ": " +
                      @applicant.name + "  (" +
                      @submission.created_at.to_date.to_s + ")",
                  body: sanitize((render partial: "edit"), :tags=>[]) ) %>
    <% end %>
  </div>
  <div class="submission-show-body">
    <%= render partial: "edit" %>
  </div>
</div>

app/views/submissions/index.html.erb
<%= render partial: "layouts/index_template" %>

app/views/submissions/show.html.erb
<div class="submission-show">
  <div class="header-bar">
    <% if @submission %>
      <%= mail_to('', 'Email this Application',
                  subject: @submission.submission_template.name + ": " +
                      @applicant.name + "  (" +
                      @submission.created_at.to_date.to_s + ")",
                  body: sanitize((render partial: "edit"), :tags=>[]) ) %>
    <% end %>
  </div>
  <div class="submission-show-body">
    <%= render partial: "edit" %>
  </div>
</div>